

export default function(){
  return {
    order: [
      "activeCards",
      "titleOne",
      "card_name",
      "typeSpecialization",
      "salary",
      "coords",
      "industry",
      "about",
      "titleFive",
      "typeWork",
      "titleTwo",
      "companyWork",
      "titleThree",
      "education",
      "institution",
      "lang",
      "titleFour",
      "car_exp",
      "additional",
    ],
    card_name:{
      type:"text", 
      name: "card_name",  
      placeholder: "Желаемая должность", 
      label:"Желаемая должность", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
    },
    about:{
      type:"textarea", 
      name: "about",  
      placeholder: "Обо мне", 
      label:"Обо мне", 
      wrapClass: "col-12 account-item"
    },
    salary: { 
      type: "multy", 
      mainname: "salary", 
      wrapClass: "col-12 account-item",
      allFields: [
        { 
          type:"text", 
          name: "price",  
          label:"Зарплата",  
          placeholder: "Укажите сумму", 
          length: "col-6 account-item"
        },
        { 
          type:"select", 
          name: "priceType",  
          length: "col-6  account-item",
          label:"Тип оплаты",  
          placeholder:"Тип оплат",
          options: [
            {label:"Руб./Смена", value:"type1"}, 
            {label:"Руб./Час", value:"type2"}, 
            {label:"Руб./Месяц", value:"type3"}, 
            {label:"За проект", value:"type4"}, 
          ]
        },
        { 
          type:"select", 
          name: "worktype",  
          length: "col-6 ",
          label:"Тип работы",
          placeholder:"Выберете тип работы",
          options: [
            {label: "Постоянная работа", value:"type_1"},
            {label: "Ночная работы", value:"type_2"},
            {label: "Сдельная работа / Подмена", value:"type_3"},
            {label: "Срочная работа", value:"type_4"},
            {label: "Консалтинг", value:"type_5"},
            {label: "Фриланс", value:"type_6"},
          ]
        },
        { 
          type:"select", 
          name: "worktime",  
          length: "col-6",
          label:"Тип занятости",
          placeholder:"Выберете тип занятости",
          options: [
            {label: "Полная", value:"type_1"},
            {label: "Частичная", value:"type_2"},
            {label: "Волонтерство", value:"type_3"},
            {label: "Стажировка", value:"type_4"},
            {label: "Подработка", value:"type_5"},
          ]
        },
      ],
    },
    coords: { 
      type:"coords", 
      name: "coords",  
      placeholder: "Адрес", 
      label: "Адрес",
      wrapClass: "col-12 account-item",

    },
    titleOne: {
      type:"title",
      label:"Основная информация", 
      wrapClass: 'col-12'
    },
    titleTwo: {
      type:"title",
      label:"Сведения о работе", 
      wrapClass: "col-12",
    },
    titleThree: {
      type:"title",
      label:"Образование", 
      wrapClass: "col-12",
    },
    titleFour: {
      type:"title",
      label:"Дополнительно", 
      wrapClass: "col-12",
    },
    titleFive: {
      type:"title",
      label:"Дополнительные условия занятости", 
      wrapClass: "col-12",
    },
    industry: {
      type: "list", 
      name: "industry", 
      label:"В какой сфере вы хотите работать?", 
      wrapClass: "col-12 account-item",
      options:[
        {label: "Бар", value:"type_1"},
        {label: "Вендинг", value:"type_2"},
        {label: "Винная", value:"type_3"},
        {label: "Винодельня", value:"type_4"},
        {label: "Гостиница", value:"type_5"},
        {label: "Кейтеринг", value:"type_6"},
        {label: "Кондитерская", value:"type_7"},
        {label: "Кофейня", value:"type_8"},
        {label: "Отель", value:"type_9"},
        {label: "Пекарня", value:"type_10"},
        {label: "Вендинг", value:"type_11"},
        {label: "Пивная", value:"type_12"},
        {label: "Пищевой завод", value:"type_13"},
        {label: "Пиццерия", value:"type_14"},
        {label: "Развлечения", value:"type_15"},
        {label: "Реклама", value:"type_16"},
        {label: "Ресторан", value:"type_17"},
        {label: "Сыроварня", value:"type_18"},
        {label: "Фаст Фуд", value:"type_19"},
        {label: "Франчайзинг", value:"type_20"},
        {label: "Частная ферма", value:"type_21"},
      ]
    },
    typeSpecialization: {
      type: "list", 
      name: "specialization", 
      label:"Специализация сотрудника?", 
      wrapClass: "col-12 account-item",
      options:[
        {label: "Администратор", value:"spec_1"},
        {label: "Водитель", value:"spec_2"},
        {label: "Горничная", value:"spec_3"},
        {label: "Диджей", value:"spec_4"},
      ]
    },
    companyWork: {
      type: "complex", 
      name: "companyWorkComplex", 
      label:"Организация",  
      wrapClass: "col-12 account-item",
      btnAddText: "Добавить организацию",
      allFields: [
        { 
          type:"text", 
          name: "namework", 
          placeholder: "Какую должность вы занимали?", 
          wrapClass: "col-6" 
        },
        { 
          type:"text", 
          name: "namecompany", 
          placeholder: "Как называлась организация?",
          wrapClass: "col-6" 
        },
        { 
          type:"textarea", 
          name: "workresp", 
          placeholder: "Обязанности", 
          maxLength: 500,
          wrapClass: "col-12" 
        },
        { 
          type:"date", 
          name: "workfrom", 
          placeholder: "Период работы c", 
          maxLength: 500,
          wrapClass: "col-6" 
        },
        { 
          type:"date", 
          name: "workto", 
          placeholder: "Период работы До", 
          maxLength: 500,
          wrapClass: "col-6" 
        },
      ],
    },
    lang: {
      type: "complex", 
      name: "lang", 
      label:"Владение языками", 
      btnAddText:"Добавить язык", 
      wrapClass: "col-12 account-item",
      allFields: [
        { 
          type:"select", 
          name: "namelang", 
          label: "Язык",
          placeholder: "Язык", 
          wrapClass: "col-6",
          options: [
            { label: 'Английский язык', value: 'type1' },
            { label: 'Немецкий язык', value: 'type2' },
            { label: 'Французский язык', value: 'type3' },
            { label: 'Испанский язык', value: 'type4' },
            { label: 'Итальянский язык', value: 'type5' },
            { label: 'Арабский язык', value: 'type6' },
            { label: 'Армянский язык', value: 'type7' },
            { label: 'Башкирский язык', value: 'type8' },
            { label: 'Белорусский язык', value: 'type9' },
            { label: 'Болгарский язык', value: 'type10' },
            { label: 'Венгерский язык', value: 'type11' },
            { label: 'Нидерландский язык', value: 'type12' },
            { label: 'Греческий язык', value: 'type13' },
            { label: 'Грузинский язык', value: 'type14' },
            { label: 'Датский язык', value: 'type15' },
            { label: 'Иврит', value: 'type16' },
            { label: 'Китайский язык', value: 'type17' },
            { label: 'Корейский язык', value: 'type18' },
            { label: 'Латынь', value: 'type19' },
            { label: 'Латышский язык', value: 'type21' },
            { label: 'Литовский язык', value: 'type22' },
            { label: 'Молдавский язык', value: 'type23' },
            { label: 'Монгольский язык', value: 'type24' },
            { label: 'Норвежский язык', value: 'type25' },
            { label: 'Осетинский язык', value: 'type26' },
            { label: 'Персидский язык', value: 'type27' },
            { label: 'Польский язык', value: 'type28' },
            { label: 'Португальский язык', value: 'type29' },
            { label: 'Румынский язык', value: 'type30' },
            { label: 'Сербский язык', value: 'type31' },
            { label: 'Словацкий язык', value: 'type32' },
            { label: 'Таджикский язык', value: 'type33' },
            { label: 'Татарский язык', value: 'type34' },
            { label: 'Турецкий язык', value: 'type35' },
            { label: 'Туркменский язык', value: 'type36' },
            { label: 'Узбекский язык', value: 'type37' },
            { label: 'Украинский язык', value: 'type38' },
            { label: 'Фарси', value: 'type39' },
            { label: 'Финский язык', value: 'type40' },
            { label: 'Хинди', value: 'type41' },
            { label: 'Чешский язык', value: 'type42' },
            { label: 'Чувашский язык', value: 'type43' },
            { label: 'Шведский язык', value: 'type44' },
            { label: 'Эсперанто', value: 'type45' },
            { label: 'Эстонский язык', value: 'type46' },
            { label: 'Японский язык', value: 'type47' },
            { label: 'Азербайджанский язык', value: 'type48' },
            { label: 'Хорватский язык', value: 'type49' },
            { label: 'Словенский язык', value: 'type50' },
            { label: 'Киргизский язык', value: 'type51' },
            { label: 'Урду', value: 'type52' },
            { label: 'Пушту', value: 'type53' },
            { label: 'Тайский язык', value: 'type54' },
            { label: 'Дагестанский язык', value: 'type55' },
            { label: 'Албанский язык', value: 'type56' },
            { label: 'Чеченский язык', value: 'type57' },
            { label: 'Кумыкский язык', value: 'type58' },
            { label: 'Русский язык', value: 'type59' },
            { label: 'Аварский язык', value: 'type60' },
            { label: 'Бурятский язык', value: 'type61' },
            { label: 'Езидский язык', value: 'type62' },
            { label: 'Ингушский язык', value: 'type63' },
            { label: 'Исландский язык', value: 'type64' },
            { label: 'Кабардинский язык', value: 'type65' },
            { label: 'Карельский язык', value: 'type66' },
            { label: 'Лакский язык', value: 'type67' },
            { label: 'Лезгинский язык', value: 'type68' },
            { label: 'Марийский язык', value: 'type69' },
            { label: 'Тувинский язык', value: 'type70' },
            { label: 'Фламандский язык', value: 'type71' },
            { label: 'Ханты-манси', value: 'type72' },
            { label: 'Черкесский язык', value: 'type73' },
            { label: 'Вьетнамский язык', value: 'type74' },
            { label: 'Дари', value: 'type75' },
            { label: 'Талышский язык', value: 'type76' },
            { label: 'Индонезийский язык', value: 'type77' },
            { label: 'Македонский язык', value: 'type78' },
            { label: 'Боснийский язык', value: 'type79' },
            { label: 'Амхарский язык', value: 'type80' },
            { label: 'Африкаанс', value: 'type81' },
            { label: 'Бенгальский язык', value: 'type82' },
            { label: 'Лаосский язык', value: 'type83' },
            { label: 'Малайский язык', value: 'type84' },
            { label: 'Суахили', value: 'type85' },
            { label: 'Тагальский язык', value: 'type86' },
            { label: 'Уйгурский язык', value: 'type87' },
            { label: 'Якутский язык', value: 'type88' },
            { label: 'Каталанский язык', value: 'type89' },
            { label: 'Баскский язык', value: 'type90' },
            { label: 'Ирландский язык', value: 'type91' },
            { label: 'Курдский язык', value: 'type92' },
            { label: 'Непальский язык', value: 'type93' },
            { label: 'Пенджаби', value: 'type94' },
            { label: 'Сомалийский язык', value: 'type95' },
            { label: 'Тамильский язык', value: 'type96' },
            { label: 'Тибетский язык', value: 'type97' },
            { label: 'Бирманский язык', value: 'type98' },
            { label: 'Мальтийский язык', value: 'type99' },
          ] 
        },
        { 
          type:"select", 
          name: "explang", 
          label: "Уровень владения",
          placeholder: "Уровень владения", 
          wrapClass: "col-6",
          options: [
            { label: 'Базовый', value: 'type1' },
            { label: 'Технический', value: 'type2' },
            { label: 'Разговорный', value: 'type3' },
            { label: 'Свободное владение', value: 'type4' },
          ] 
        },
      ],
    },
    education: { 
      type:"select", 
      name: "education",
      label:"Уровень", 
      placeholder: "Выбрать образование",
      wrapClass: "col-12 account-item",
      options: [
        { label: 'Среднее', value: 'type1' },
        { label: 'Неоконченное высшее', value: 'type2' },
        { label: 'Бакалавр', value: 'type3' },
        { label: 'Средне специальное', value: 'type4' },
        { label: 'Высшее', value: 'type5' },
        { label: 'Магистр', value: 'type6' },
      ] 
    },
    institution: {
      type: "complex", 
      name: "institution", 
      label: "Место образование",
      wrapClass: "col-12 account-item",
      btnAddText: "Добавить место обучения",
      allFields: [
        { 
          type:"text", 
          name: "place", 
          placeholder: "Учебное заведение", 
          wrapClass: "col-6" 
        },
        { 
          type:"text", 
          name: "faculty", 
          placeholder: "Факультет",
          wrapClass: "col-6" 
        },
        { 
          type:"text", 
          name: "specialization", 
          placeholder: "Специализация", 
          wrapClass: "col-6" 
        },
        { 
          type:"date", 
          name: "dateEnd", 
          placeholder: "Год окончания", 
          maxLength: 500,
          wrapClass: "col-6" 
        },

      ],
    },
    car_exp: { 
      type: "select", 
      name: "car_exp", 
      label: "Опыт вождения", 
      placeholder: "Опыт вождения", 
      wrapClass: "col-12 account-item",
      options:[
        {label: "A", value:"type_1"},
        {label: "B", value:"type_2"},
        {label: "C", value:"type_3"},
        {label: "D", value:"type_4"},
        {label: "E", value:"type_5"},
      ]
    },    
    additional: {
      type:"checkbox", 
      name: "additional",
      wrapClass: "col-12 account-item",
      options: [
        { label: 'Есть ИП/Самозанятый', value: 'type_1' },
        { label: 'Медицинская книжка', value: 'type_2' },
        { label: 'Готовность к командировкам', value: 'type_3' },
        { label: 'Готовность работать ночью', value: 'type_4' },
        { label: 'Срочный выезд', value: 'type_5' },
        { label: 'Разрешение на работу в России', value: 'type_6' },
        { label: 'Гражданство РФ', value: 'type_7' },
      ] 
    },
    typeWork: {
      type:"checkbox", 
      name: "typeWork",
      wrapClass: "col-12 account-item",
      options: [
        {label: "Постоянная работа", value:"type_1"},
        {label: "Ночная работы", value:"type_2"},
        {label: "Сдельная работа / Подмена", value:"type_3"},
        {label: "Срочная работа", value:"type_4"},
        {label: "Фриланс", value:"type_6"},
      ] 
    },
    activeCards: {
      type:"switch",
      name: "activeCards", 
      label: "Статус", 
      options: [
        {name:"Активно",value:"on"},
        {name:"Не активно", value:"off"},
      ],
      wrapClass: "col-12 account-item"
    },
  }
}