

export default function(){
  return {
    order: [
      "activeCards",
      "card_name",
      "card_mail",
      "card_phone",
      "card_site",
      "cards_coords",
      "cards_description_mini",
      "cards_description_full",
      "cards_photo",
      "cards_logo",
      "cards_photos",
      "specialization",
      "breeds",

    ],
    card_name:{
      type:"text", 
      name: "card_name",  
      placeholder: "Наименование питомника*", 
      label:"Наименование питомника*", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
    },
    card_site:{
      type:"text", 
      name: "card_site",  
      placeholder: "Сайт питомника", 
      label:"Сайт питомника", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
    },
    card_mail:{
      type:"text", 
      name: "card_mail",  
      placeholder: "Email питомника", 
      label:"Email питомника", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
    },
    card_phone:{
      type:"phone", 
      name: "card_phone",  
      placeholder: "Телефон питомника", 
      label:"Телефон питомника", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
    },
    cards_coords: { 
      type:"coords", 
      name: "cards_coords",  
      placeholder: "Адрес", 
      label: "Адрес питомника",
      wrapClass: "col-12 account-item",
    },
    cards_description_mini:{
      type:"textarea", 
      name: "cards_description_mini",  
      placeholder: "Краткое описание питомника", 
      label:"Краткое описание питомника", 
      wrapClass: "col-12 account-item"
    },
    cards_description_full:{
      type:"textarea", 
      name: "cards_description_full",  
      placeholder: "Полное описание питомника", 
      label:"Полное описание питомника", 
      wrapClass: "col-12 account-item"
    },    
    cards_photo: {
      type: "file", 
      name: "cards_photo", 
      label:"Фото питомника", 
      labelSecond:"(Изображение формата jpg,png не менее 150x150 px, не более 8Мб)", 
      typeFile: "img", 
      typeUpload:".png, .jpg, .jpeg", 
      maxSize: 5242880, 
      textEmpty: "На данный момент фоно не выбрано",
      wrapClass: "col-12 col-lg-3 col-sm-5 account-item"
    },
    cards_logo: {
      type: "file", 
      name: "cards_logo", 
      label:"Лого питомника", 
      labelSecond:"(Изображение формата jpg,png не менее 150x150 px, не более 8Мб)", 
      typeFile: "img", 
      typeUpload:".png, .jpg, .jpeg", 
      maxSize: 5242880, 
      textEmpty: "На данный момент фоно не выбрано",
      wrapClass: "col-12 col-lg-3 col-sm-5 account-item"
    },
    cards_photos: {
      type: "file", 
      name: "cards_photos", 
      label:"Фотографии питомника", 
      labelSecond:"(Изображение формата jpg,png не менее 150x150 px, не более 8Мб)", 
      typeFile: "img", 
      typeUpload:".png, .jpg, .jpeg", 
      maxSize: 5242880, 
      textEmpty: "На данный момент фоно не выбрано",
      wrapClass: "col-12 col-lg-3 col-sm-5 account-item"
    },
    specialization: {
      type: "list", 
      name: "specialization", 
      label:"Специализация питомника", 
      wrapClass: "col-12 account-item",
      options:[
        {label: "Бар", value:"type_1"},
        {label: "Вендинг", value:"type_2"},
        {label: "Винная", value:"type_3"},
        {label: "Винодельня", value:"type_4"},
        {label: "Гостиница", value:"type_5"},
        {label: "Кейтеринг", value:"type_6"},
        {label: "Кондитерская", value:"type_7"},
        {label: "Кофейня", value:"type_8"},
        {label: "Отель", value:"type_9"},
        {label: "Пекарня", value:"type_10"},
        {label: "Вендинг", value:"type_11"},
        {label: "Пивная", value:"type_12"},
        {label: "Пищевой завод", value:"type_13"},
        {label: "Пиццерия", value:"type_14"},
        {label: "Развлечения", value:"type_15"},
        {label: "Реклама", value:"type_16"},
        {label: "Ресторан", value:"type_17"},
        {label: "Сыроварня", value:"type_18"},
        {label: "Фаст Фуд", value:"type_19"},
        {label: "Франчайзинг", value:"type_20"},
        {label: "Частная ферма", value:"type_21"},
      ]
    },
    breeds: {
      type: "list", 
      name: "breeds", 
      label:"Породы питомника", 
      wrapClass: "col-12 account-item",
      options:[
        {label: "Бар", value:"type_1"},
        {label: "Вендинг", value:"type_2"},
        {label: "Винная", value:"type_3"},
        {label: "Винодельня", value:"type_4"},
        {label: "Гостиница", value:"type_5"},
        {label: "Кейтеринг", value:"type_6"},
        {label: "Кондитерская", value:"type_7"},
        {label: "Кофейня", value:"type_8"},
        {label: "Отель", value:"type_9"},
        {label: "Пекарня", value:"type_10"},
        {label: "Вендинг", value:"type_11"},
        {label: "Пивная", value:"type_12"},
        {label: "Пищевой завод", value:"type_13"},
        {label: "Пиццерия", value:"type_14"},
        {label: "Развлечения", value:"type_15"},
        {label: "Реклама", value:"type_16"},
        {label: "Ресторан", value:"type_17"},
        {label: "Сыроварня", value:"type_18"},
        {label: "Фаст Фуд", value:"type_19"},
        {label: "Франчайзинг", value:"type_20"},
        {label: "Частная ферма", value:"type_21"},
      ]
    },
    activeCards: {
      type:"switch",
      name: "activeCards", 
      label: "Статус", 
      options: [
        {name:"Активно",value:"on"},
        {name:"Не активно", value:"off"},
      ],
      wrapClass: "col-12 account-item"
    },
  }
}